### ISSUE TITLE
Shortcuts.design future vision

### ISSUE THREAD

**Issue by michelvanheest** [michelvanheest/shortcuts-design-data#12]
# Shortcuts.design future vision

## Trying to ship things more often

9 months ago, I launched [Shortcuts.design](https://shortcuts.design/). 4 months ago it became possible for users to edit or add content through this GitHub repository. 

For multiple reasons, updates always took a long time to launch: 

1. I'm a student and Shortcuts.design isn't my main focus at the moment
2. I wanted to cluster changes before I pushed them live
3. My coding skills aren't that good so most of the website is hard coded from the beginning

I want to introduce a quicker release cycle by not shipping clustered updates anymore but by shipping every single feature I built when it's ready. Also, I want to make my plans for this website more transparent by posting them down below. 
<br> In this way, you know what to expect, we can start a discussion about the future of this website or you can help out if you want.

If you have feature requests, questions or good plans for the future of Shortcuts.design, feel free to post a comment on this issue, [Tweet](https://twitter.com/michelvanheest) or [e-mail](mailto:shortcutsdesign@michelvanheest.com?subject=Mail%20from%20Shortcuts.design) me.

### General
- [x] Write this GitHub issue
- [ ] ~~Add a chat button or an alternative way to quickly contact me with feature requests or any other questions~~ --> Hotjar 'feedback' button is enough for now
- [ ] Write better explanation for editing/adding new tools

### Design
- [x] Design a search or filter for the toolspages and redesign the top part of the toolspages
- [x] Give the particles on the homepage better matching colors 😇

### Development
- [x] Add a search or filter for the toolspages and build the new design for the toolspages
- [x] Fix ugly particles on mobile
- [x] Fix margin and padding issues tools-icons on smaller screens
- [x] Refactor old stylesheets that are an ass to maintain
- [ ] Make data better maintainable for contributors
	- Currently, there's still a lot of really _not_ maintainable code, like the data on the tools-pages in hardcoded HTML tables. The legacy code is because of me only knowing basic HTML and CSS while creating the first version of this website.
- [ ] Add scroll to top button
- [ ] Create 'empty' state for when the search query doesn't deliver results
- [ ] Add fancy moving particles to the homepage ✨

### Tools
- [ ] Add new tools-section: Productivity
- [ ] Delete/comment out all grayed out on the homepage
- [ ] Add new tools to current sections

**Comment by thgh** [comment]
How about using a static site generator and letting it build the project on every commit on master?
Netlify would make this quite easy.

**Comment by michelvanheest** [comment]
> How about using a static site generator and letting it build the project on every commit on master?
> Netlify would make this quite easy.

@thgh Thanks for your reply, a while ago 😅 Haven't had the time to work on it for quiet some time, but I'm actually working on an update which indeed uses 11ty and Netlify. Thanks!
