### ISSUE TITLE
The design principle of keyboard shortcut.

### ISSUE THREAD

**Issue by willemswang** [michelvanheest/shortcuts-design-data#29]
Your repo is a great project.👍
I can find and learn a lot of shortcuts for commonly used software here, which has benefited me a lot. 🤩
But rather than what these shortcuts are, I'm more curious about why they are made that way. 🧐
If we know why it was designed this way, I think it would be more effective for us to learn & remember & understand & create a shortcut to use.🤗
I have found several articles on this topic. It can be found in the list below. Although they have solved my problem to some extent, I still feel that I have not found a design philosophy. 🤔

- https://news.ycombinator.com/item?id=7752698
- https://liferay.design/articles/best-practices/hotkey-design/
- http://ui-patterns.com/patterns/keyboard-shortcuts

**Comment by michelvanheest** [comment]
@willemswang Thanks for taking the time to write this message and letting me know you got great use of the project, it means a lot to me 😄

Tbh, I never really thought about the model and the _why_ behind designing shortcuts as an input-method, but now you mentioned it, it got me interested. Thanks for sharing these links, I added them to my read-later list to go through 😄
