### ISSUE TITLE
Addition to design tools: Overflow

### ISSUE THREAD

**Issue by animify** [michelvanheest/shortcuts-design-data#5]
Hi Michel!

Loving the platform! Requesting the addition of [Overflow](https://overflow.io/) to the design tools list. Sending over a PR in a sec. Attached our PNG logo below, let me know if you need anything else.

Cheers

![overflow icon color](https://user-images.githubusercontent.com/10724744/41148031-977fcb12-6b10-11e8-8844-9e329beb17a5.png)

**Comment by michelvanheest** [comment]
Gonna add Overflow today! Thanks for all the help! See Hi to the Proto.io team as well from me ;)

**Comment by animify** [comment]
Thanks Michel, will do!
