### ISSUE TITLE
Add separate OS commands for zoom

### ISSUE THREAD

**Issue by cyber-panther** [michelvanheest/shortcuts-design-data#64]
the commands for zoom are mixed up with some having mac commands and some windows ones, can I update the code to make two separate HTML files having separate commands.

**Comment by michelvanheest** [comment]
Sure thing!! Go ahead @cyber-panther :)

**Comment by cyber-panther** [comment]
hi @michelvanheest,

I updated the commands, please check the PR for the same.

thanks and have a nice day, happy coding...

**Comment by michelvanheest** [comment]
Hey @cyber-panther should be live now! Thanks! :)
